# -*- coding: utf-8 -*-
# AUTO-GENERATED by scenarios/common/python/dialogues/compile_dialogues.py
# 수동 편집 금지 — yaml 수정 후 컴파일러를 재실행하세요.
# 문서: docs/dialogue-data-pipeline.md

SOURCE_HASH = "669ef170b33f984f2e6d30f23dd1d2dbec9f1f87"
FILE_COUNT = 87


def get(rel):
    """dialogues 루트 기준 상대경로(posix)로 파싱된 dict 반환. 없으면 None."""
    if rel.startswith("characters/"):
        import dialogues_compiled.characters as m
        return m.DATA.get(rel)
    if rel.startswith("archetype_dialogues/cheerful/"):
        import dialogues_compiled.arch_cheerful as m
        return m.DATA.get(rel)
    if rel.startswith("archetype_dialogues/cold/"):
        import dialogues_compiled.arch_cold as m
        return m.DATA.get(rel)
    if rel.startswith("archetype_dialogues/devoted/"):
        import dialogues_compiled.arch_devoted as m
        return m.DATA.get(rel)
    if rel.startswith("archetype_dialogues/fierce/"):
        import dialogues_compiled.arch_fierce as m
        return m.DATA.get(rel)
    if rel.startswith("archetype_dialogues/gentle/"):
        import dialogues_compiled.arch_gentle as m
        return m.DATA.get(rel)
    if rel.startswith("archetype_dialogues/innocent/"):
        import dialogues_compiled.arch_innocent as m
        return m.DATA.get(rel)
    if rel.startswith("archetype_dialogues/proud/"):
        import dialogues_compiled.arch_proud as m
        return m.DATA.get(rel)
    if rel.startswith("archetype_dialogues/seductive/"):
        import dialogues_compiled.arch_seductive as m
        return m.DATA.get(rel)
    if rel.startswith("archetype_dialogues/stoic/"):
        import dialogues_compiled.arch_stoic as m
        return m.DATA.get(rel)
    if rel.startswith("archetype_dialogues/timid/"):
        import dialogues_compiled.arch_timid as m
        return m.DATA.get(rel)
    return None
