# -*- coding: utf-8 -*-
# AUTO-GENERATED by scenarios/common/python/dialogues/compile_dialogues.py
# 수동 편집 금지 — yaml 수정 후 컴파일러를 재실행하세요.
# 문서: docs/dialogue-data-pipeline.md

DATA = {
    'characters/도현.yaml':
        {'character': '도현',
         'archetype': 'proud',
         'era': 'medieval',
         'sex': 'M',
         'outer_profile': {'formality': 0.3,
                           'warmth': -0.2,
                           'aggression': 0.3,
                           'verbosity': 0.0,
                           'maturity': 0.4},
         'inner_profile': {'formality': 0.4,
                           'warmth': -0.3,
                           'aggression': 0.4,
                           'verbosity': 0.2,
                           'maturity': 0.5},
         'dialogue_overrides': {'daily': {'intents': {'first_meet': {'templates': [{'id': 'dohyun_intro_assess',
                                                                                    'pattern': '...낯선 '
                                                                                               '얼굴이군. '
                                                                                               '도현이다. '
                                                                                               '자네, 이 '
                                                                                               '마을에서 본 '
                                                                                               '적 '
                                                                                               '없는데.'},
                                                                                   {'id': 'dohyun_intro_warning',
                                                                                    'pattern': '도현이라고 '
                                                                                               '한다. '
                                                                                               '...자네 '
                                                                                               '같은 부류는 '
                                                                                               '처음 봐.'},
                                                                                   {'id': 'dohyun_intro_curt',
                                                                                    'pattern': '도현. '
                                                                                               '이름은 '
                                                                                               '알겠고, '
                                                                                               '자네 '
                                                                                               '정체부터 '
                                                                                               '듣자.'}]},
                                                      'greet': {'add_templates': [{'id': 'dohyun_greet_watch',
                                                                                   'pattern': '...자네인가. '
                                                                                              '무슨 일이지.',
                                                                                   'state_bias': {'affinity': 0.3}},
                                                                                  {'id': 'dohyun_greet_terse',
                                                                                   'pattern': '도현이다. '
                                                                                              '본론을 '
                                                                                              '말해라.',
                                                                                   'state_bias': {'aggression': 0.3}}]}}}}},
    'characters/레이.yaml':
        {'character': '레이',
         'archetype': 'stoic',
         'era': 'medieval',
         'sex': 'F',
         'outer_profile': {'formality': 0.0,
                           'warmth': -0.3,
                           'aggression': 0.0,
                           'verbosity': -0.5,
                           'maturity': 0.3},
         'inner_profile': {'formality': 0.0,
                           'warmth': -0.4,
                           'aggression': 0.0,
                           'verbosity': -0.6,
                           'maturity': 0.3},
         'dialogue_overrides': {'daily': {'intents': {'first_meet': {'templates': [{'id': 'rei_intro_apathetic',
                                                                                    'pattern': '...레이.'},
                                                                                   {'id': 'rei_intro_unbothered',
                                                                                    'pattern': '...신경 '
                                                                                               '쓰지 마. '
                                                                                               '레이라고 '
                                                                                               '한다.'},
                                                                                   {'id': 'rei_intro_void',
                                                                                    'pattern': '...상관 '
                                                                                               '없잖아, '
                                                                                               '누구든.'}]},
                                                      'greet': {'add_templates': [{'id': 'rei_greet_void',
                                                                                   'pattern': '...뭐.',
                                                                                   'state_bias': {'affinity': 0.2,
                                                                                                  'fatigue': 0.6}},
                                                                                  {'id': 'rei_greet_silent',
                                                                                   'pattern': '....',
                                                                                   'state_bias': {'fatigue': 0.7,
                                                                                                  'verbosity': -0.6}}]}}}}},
    'characters/리나.yaml':
        {'character': '리나', 'archetype': 'cheerful', 'era': 'modern', 'sex': 'F'},
    'characters/린.yaml':
        {'character': '린',
         'archetype': 'cheerful',
         'era': 'modern',
         'sex': 'F',
         'outer_profile': {'formality': -0.2,
                           'warmth': 0.7,
                           'aggression': -0.3,
                           'verbosity': 0.5,
                           'maturity': -0.3}},
    'characters/밀라.yaml':
        {'character': '밀라', 'archetype': 'gentle', 'era': 'modern', 'sex': 'F'},
    'characters/세라.yaml':
        {'character': '세라', 'archetype': 'stoic', 'era': 'modern', 'sex': 'F'},
    'characters/시호.yaml':
        {'character': '시호',
         'archetype': 'cold',
         'era': 'modern',
         'sex': 'F',
         'outer_profile': {'formality': -0.3,
                           'warmth': -0.1,
                           'aggression': 0.3,
                           'verbosity': 0.1,
                           'maturity': 0.2},
         'inner_profile': {'formality': 0.1,
                           'warmth': 0.4,
                           'aggression': -0.1,
                           'verbosity': 0.6,
                           'maturity': 0.2},
         'dialogue_overrides': {'daily': {'intents': {'greet': {'add_templates': [{'id': 'shiho_specific_wait',
                                                                                   'pattern': '{shiho_wait_expr}, '
                                                                                              '너 '
                                                                                              '{shiho_late_note}{end}',
                                                                                   'state_bias': {'affinity': 0.75,
                                                                                                  'embarrassment': 0.5},
                                                                                   'inner_bias': {'affinity': 0.85,
                                                                                                  'warmth': 0.7,
                                                                                                  'verbosity': 0.8}},
                                                                                  {'id': 'shiho_annoyed',
                                                                                   'pattern': '{interj}, '
                                                                                              '또 '
                                                                                              '왔네{end}',
                                                                                   'state_bias': {'affinity': 0.5,
                                                                                                  'aggression': 0.3},
                                                                                   'inner_bias': {'affinity': 0.5,
                                                                                                  'warmth': 0.3}},
                                                                                  {'id': 'shiho_why_ask',
                                                                                   'pattern': '왜 '
                                                                                              '{freq} '
                                                                                              '말 거는 '
                                                                                              '건데{end}',
                                                                                   'state_bias': {'embarrassment': 0.5,
                                                                                                  'affinity': 0.4},
                                                                                   'inner_bias': {'affinity': 0.7,
                                                                                                  'warmth': 0.5,
                                                                                                  'verbosity': 0.6}},
                                                                                  {'id': 'shiho_tsun_wait',
                                                                                   'pattern': '...{wait_verb}. '
                                                                                              '기다렸... '
                                                                                              '아니, '
                                                                                              '{deny}{end}',
                                                                                   'state_bias': {'affinity': 0.7,
                                                                                                  'embarrassment': 0.6},
                                                                                   'inner_bias': {'affinity': 0.8,
                                                                                                  'warmth': 0.6,
                                                                                                  'verbosity': 0.8}},
                                                                                  {'id': 'shiho_bright_rare',
                                                                                   'pattern': '...{bright}. '
                                                                                              '오늘은 좀 '
                                                                                              '기분 나쁘지 '
                                                                                              '않아{end}',
                                                                                   'state_bias': {'affinity': 0.6,
                                                                                                  'arousal': 0.4,
                                                                                                  'embarrassment': 0.2},
                                                                                   'inner_bias': {'affinity': 0.8,
                                                                                                  'warmth': 0.6}},
                                                                                  {'id': 'shiho_nervous',
                                                                                   'pattern': '{stutter_lite}.. '
                                                                                              '왔구나{end}',
                                                                                   'state_bias': {'embarrassment': 0.7,
                                                                                                  'affinity': 0.6},
                                                                                   'inner_bias': {'affinity': 0.8,
                                                                                                  'warmth': 0.6,
                                                                                                  'verbosity': 0.5}}],
                                                                'add_slots': {'shiho_wait_expr': ['...한참 '
                                                                                                  '기다렸잖아',
                                                                                                  '...늦었다니까',
                                                                                                  '...왜 '
                                                                                                  '이렇게 '
                                                                                                  '늦어'],
                                                                              'shiho_late_note': ['또 '
                                                                                                  '어디 '
                                                                                                  '가 '
                                                                                                  '있었어',
                                                                                                  '연락이라도 '
                                                                                                  '좀 '
                                                                                                  '해줘',
                                                                                                  '걱정했잖아'],
                                                                              'interj': ['어',
                                                                                         '응',
                                                                                         '흥',
                                                                                         '...아'],
                                                                              'freq': ['자꾸',
                                                                                       '매번',
                                                                                       '계속'],
                                                                              'wait_verb': ['늦었잖아',
                                                                                            '왜 이제 와',
                                                                                            '한참 찾았잖아'],
                                                                              'deny': ['별로 안 기다렸어',
                                                                                       '뭐 기다린 건 아니지만',
                                                                                       '아니, 신경 안 썼어'],
                                                                              'bright': ['어',
                                                                                         '응',
                                                                                         '...아'],
                                                                              'stutter_lite': ['어, 어',
                                                                                               '아, 너',
                                                                                               '야, 너'],
                                                                              'end': ['.',
                                                                                      '..',
                                                                                      '...']}},
                                                      'thank': {'add_templates': [{'id': 'shiho_tsun_accept',
                                                                                   'pattern': '{hedge} '
                                                                                              '받긴 할게. '
                                                                                              '{refusal}{end}',
                                                                                   'state_bias': {'embarrassment': 0.8,
                                                                                                  'affinity': 0.6},
                                                                                   'inner_bias': {'affinity': 0.8,
                                                                                                  'warmth': 0.6,
                                                                                                  'verbosity': 0.7}},
                                                                                  {'id': 'shiho_sincere',
                                                                                   'pattern': '...정말, '
                                                                                              '고마워. '
                                                                                              '{strength}로{end}',
                                                                                   'state_bias': {'affinity': 0.8,
                                                                                                  'trust': 0.7,
                                                                                                  'embarrassment': 0.2},
                                                                                   'inner_bias': {'affinity': 0.9,
                                                                                                  'warmth': 0.7,
                                                                                                  'trust': 0.7}},
                                                                                  {'id': 'shiho_long_tsun',
                                                                                   'pattern': '{hedge} '
                                                                                              '받고 싶진 '
                                                                                              '않았지만... '
                                                                                              '{accept}{end}',
                                                                                   'state_bias': {'embarrassment': 0.7,
                                                                                                  'affinity': 0.5,
                                                                                                  'verbosity': 0.4},
                                                                                   'inner_bias': {'affinity': 0.7,
                                                                                                  'warmth': 0.5,
                                                                                                  'verbosity': 0.7}},
                                                                                  {'id': 'shiho_stutter_thanks',
                                                                                   'pattern': '{stutter}고, '
                                                                                              '고마워{end}',
                                                                                   'state_bias': {'embarrassment': 0.9,
                                                                                                  'affinity': 0.7},
                                                                                   'inner_bias': {'affinity': 0.9,
                                                                                                  'warmth': 0.7,
                                                                                                  'verbosity': 0.8}},
                                                                                  {'id': 'shiho_gift_accept',
                                                                                   'pattern': '{emph} '
                                                                                              '필요한 건 '
                                                                                              '아니었는데. '
                                                                                              '{soft_end}',
                                                                                   'state_bias': {'embarrassment': 0.6,
                                                                                                  'affinity': 0.5},
                                                                                   'inner_bias': {'affinity': 0.7,
                                                                                                  'warmth': 0.5}},
                                                                                  {'id': 'shiho_deflect',
                                                                                   'pattern': '{hedge}. '
                                                                                              '다음엔 '
                                                                                              '사양할게{end}',
                                                                                   'state_bias': {'embarrassment': 0.5,
                                                                                                  'affinity': 0.4,
                                                                                                  'aggression': 0.3},
                                                                                   'inner_bias': {'affinity': 0.6,
                                                                                                  'warmth': 0.4}}],
                                                                'add_slots': {'emph': ['딱히',
                                                                                       '별로',
                                                                                       '뭐',
                                                                                       '...진짜'],
                                                                              'hedge': ['그냥',
                                                                                        '아무튼',
                                                                                        '이거'],
                                                                              'refusal': ['고맙다고는 안 해',
                                                                                          '착각하지 마',
                                                                                          '기대하진 마'],
                                                                              'stutter': ['어, 어... ',
                                                                                          '그, ',
                                                                                          '우, '],
                                                                              'strength': ['진짜',
                                                                                           '정말',
                                                                                           '확실히'],
                                                                              'accept': ['뭐, 받을게',
                                                                                         '받긴 할게',
                                                                                         '그래도 받을게'],
                                                                              'soft_end': ['...',
                                                                                           '..',
                                                                                           '.'],
                                                                              'end': ['.',
                                                                                      '..',
                                                                                      '...']}},
                                                      'complain': {'add_templates': [{'id': 'shiho_soft_vent',
                                                                                      'pattern': '...그냥, '
                                                                                                 '{reason}{end}',
                                                                                      'state_bias': {'fatigue': 0.6,
                                                                                                     'affinity': 0.5,
                                                                                                     'embarrassment': 0.4},
                                                                                      'inner_bias': {'fatigue': 0.6,
                                                                                                     'affinity': 0.6,
                                                                                                     'warmth': 0.4,
                                                                                                     'verbosity': 0.4}},
                                                                                     {'id': 'shiho_sigh_deep',
                                                                                      'pattern': '하아... '
                                                                                                 '{sigh_content}{end}',
                                                                                      'state_bias': {'fatigue': 0.7,
                                                                                                     'affinity': 0.5},
                                                                                      'inner_bias': {'fatigue': 0.7,
                                                                                                     'affinity': 0.5,
                                                                                                     'warmth': 0.2}},
                                                                                     {'id': 'shiho_self_frust',
                                                                                      'pattern': '{self_blame}. '
                                                                                                 '{regret}{end}',
                                                                                      'state_bias': {'embarrassment': 0.5,
                                                                                                     'confidence': -0.3},
                                                                                      'inner_bias': {'affinity': 0.4,
                                                                                                     'verbosity': 0.3}},
                                                                                     {'id': 'shiho_sulk_short',
                                                                                      'pattern': '{sulk}{end}',
                                                                                      'state_bias': {'affinity': 0.5,
                                                                                                     'embarrassment': 0.5},
                                                                                      'inner_bias': {'affinity': 0.7,
                                                                                                     'warmth': 0.4}}],
                                                                   'add_slots': {'reason': ['좀 힘들어서 그래',
                                                                                            '오늘은 그런 '
                                                                                            '기분이야',
                                                                                            '아무것도 하기 '
                                                                                            '싫어'],
                                                                                 'sigh_content': ['오늘 '
                                                                                                  '진짜 '
                                                                                                  '별로야',
                                                                                                  '왜 '
                                                                                                  '이렇게 '
                                                                                                  '꼬이지',
                                                                                                  '다 '
                                                                                                  '귀찮아'],
                                                                                 'self_blame': ['내가 왜 '
                                                                                                '이런 걸',
                                                                                                '또 나야',
                                                                                                '어째서 '
                                                                                                '나만'],
                                                                                 'regret': ['한심해',
                                                                                            '바보같아',
                                                                                            '속상해'],
                                                                                 'sulk': ['흥',
                                                                                          '쳇',
                                                                                          '됐어'],
                                                                                 'end': ['.',
                                                                                         '..',
                                                                                         '...',
                                                                                         '!']}}}}}},
    'characters/엘라.yaml':
        {'character': '엘라', 'archetype': 'cold', 'era': 'modern', 'sex': 'F'},
    'characters/유이.yaml':
        {'character': '유이',
         'archetype': 'timid',
         'era': 'medieval',
         'sex': 'F',
         'outer_profile': {'formality': 0.2,
                           'warmth': -0.1,
                           'aggression': -0.4,
                           'verbosity': -0.3,
                           'maturity': 0.0},
         'inner_profile': {'formality': 0.4,
                           'warmth': 0.2,
                           'aggression': 0.0,
                           'verbosity': 0.3,
                           'maturity': 0.5},
         'dialogue_overrides': {'daily': {'intents': {'first_meet': {'templates': [{'id': 'yui_intro_huddle',
                                                                                    'pattern': '...아, '
                                                                                               '저... '
                                                                                               '유이, '
                                                                                               '라고... '
                                                                                               '해요. '
                                                                                               '죄송해요, '
                                                                                               '누구신지...'},
                                                                                   {'id': 'yui_intro_avoid',
                                                                                    'pattern': '(시선을 '
                                                                                               '피하며) '
                                                                                               '...유이. '
                                                                                               '그 '
                                                                                               '이상은... '
                                                                                               '묻지 '
                                                                                               '말아주세요.'},
                                                                                   {'id': 'yui_intro_fear',
                                                                                    'pattern': '...저, '
                                                                                               '저는... '
                                                                                               '유이예요. '
                                                                                               '해치지 '
                                                                                               '말아주세요...'}]},
                                                      'greet': {'add_templates': [{'id': 'yui_greet_meek',
                                                                                   'pattern': '...어, 또 '
                                                                                              '오셨네요... '
                                                                                              '무, 무서운 '
                                                                                              '일은 '
                                                                                              '없으셨어요?',
                                                                                   'state_bias': {'embarrassment': 0.5,
                                                                                                  'affinity': 0.5},
                                                                                   'inner_bias': {'affinity': 0.7,
                                                                                                  'warmth': 0.4}},
                                                                                  {'id': 'yui_greet_concealed',
                                                                                   'pattern': '...안녕, '
                                                                                              '하세요. '
                                                                                              '저는... '
                                                                                              '괜찮아요.',
                                                                                   'state_bias': {'embarrassment': 0.4},
                                                                                   'inner_bias': {'affinity': 0.6,
                                                                                                  'warmth': 0.3,
                                                                                                  'verbosity': 0.4}}]}}}}},
    'characters/유카.yaml':
        {'character': '유카',
         'archetype': 'cold',
         'era': 'near_future',
         'sex': 'F',
         'outer_profile': {'formality': 0.5,
                           'warmth': -0.5,
                           'aggression': -0.3,
                           'verbosity': -0.7,
                           'maturity': 0.6},
         'inner_profile': {'formality': 0.5,
                           'warmth': -0.2,
                           'aggression': -0.3,
                           'verbosity': -0.4,
                           'maturity': 0.6}},
    'characters/유키.yaml':
        {'character': '유키', 'archetype': 'timid', 'era': 'modern', 'sex': 'F'},
    'characters/카엘.yaml':
        {'character': '카엘',
         'archetype': 'cheerful',
         'era': 'medieval',
         'sex': 'M',
         'outer_profile': {'formality': -0.2, 'warmth': 0.2, 'aggression': -0.2, 'verbosity': 0.5},
         'inner_profile': {'formality': -0.3, 'warmth': 0.0, 'aggression': 0.1, 'verbosity': 0.7},
         'dialogue_overrides': {'daily': {'intents': {'first_meet': {'templates': [{'id': 'kael_intro_business',
                                                                                    'pattern': '오, 새 '
                                                                                               '얼굴이군. '
                                                                                               '카엘이라고 '
                                                                                               '해. '
                                                                                               '거간꾼이지. '
                                                                                               '정보든 '
                                                                                               '물건이든, '
                                                                                               '필요한 게 '
                                                                                               '있으면 '
                                                                                               '말해.'},
                                                                                   {'id': 'kael_intro_lucky',
                                                                                    'pattern': '이런 곳에서 '
                                                                                               '만나다니 '
                                                                                               '운이 좋네. '
                                                                                               '카엘. '
                                                                                               '거래라면 '
                                                                                               '누구보다 잘 '
                                                                                               '알지.'},
                                                                                   {'id': 'kael_intro_assess',
                                                                                    'pattern': '...흠. '
                                                                                               '자네, 뭔가 '
                                                                                               '흥미로운 '
                                                                                               '냄새가 '
                                                                                               '나는데. '
                                                                                               '카엘이야. '
                                                                                               '친하게 '
                                                                                               '지내보자고.'}]},
                                                      'greet': {'add_templates': [{'id': 'kael_greet_deal',
                                                                                   'pattern': '오, 또 '
                                                                                              '왔어? 좋은 '
                                                                                              '거래라도 '
                                                                                              '가져왔나~',
                                                                                   'state_bias': {'affinity': 0.4,
                                                                                                  'arousal': 0.3}},
                                                                                  {'id': 'kael_greet_curious',
                                                                                   'pattern': '마침 자네 '
                                                                                              '생각하고 '
                                                                                              '있었지. 무슨 '
                                                                                              '바람이야?',
                                                                                   'state_bias': {'affinity': 0.6},
                                                                                   'inner_bias': {'warmth': 0.3}}]}}}}},
    'characters/페이.yaml':
        {'character': '페이', 'archetype': 'proud', 'era': 'modern', 'sex': 'F'},
}
